name: .NET

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
 
jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - name: Publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
      
    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v2
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp
  
  deploy-1:
      name: 'Deploy DEV'
      runs-on: ubuntu-latest
      needs: build
      environment: 
        name: 'DEV'
        
      steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app
          
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: web-gh-test
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }} 
          package: .
  
  deploy-2:
      name: 'Deploy QA'
      runs-on: ubuntu-latest
      needs: deploy-1
      environment: 
        name: 'QA'
        
      steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app
          
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: web-gh-test
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }} 
          package: .
